/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/*.html"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    "max-w-[80vw]",
    "chat-message",
    "flex",
    "items-end",
    "justify-end",
    "flex-col",
    "space-y-2",
    "text-xs",
    "text-sm",
    "text-base",
    "max-w-xs",
    "mx-2",
    "items-start",
    "px-4",
    "py-2",
    "rounded-lg",
    "inline-block",
    "rounded-bl-none",
    "bg-gray-100",
    "text-gray-600",
    "w-6",
    "h-6",
    "rounded-full",
    "order-2",
    "flex",
    "items-center",
    "justify-center",
    "space-x-2",
    "animate-pulse",
    "w-2",
    "h-2",
    "bg-blue-400",
    "rounded-full",
    "bg-emerald-600"
  ]
}

